<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNAiwAhp\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNAiwAhp/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerNAiwAhp.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerNAiwAhp\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerNAiwAhp\App_KernelProdContainer([
    'container.build_hash' => 'NAiwAhp',
    'container.build_id' => '82e22e9d',
    'container.build_time' => 1582308206,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNAiwAhp');
