<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYotL08x\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYotL08x/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYotL08x.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYotL08x\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYotL08x\App_KernelDevDebugContainer([
    'container.build_hash' => 'YotL08x',
    'container.build_id' => 'a83a10f7',
    'container.build_time' => 1582308190,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYotL08x');
