<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXKU5XO0\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXKU5XO0/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXKU5XO0.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXKU5XO0\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXKU5XO0\App_KernelDevDebugContainer([
    'container.build_hash' => 'XKU5XO0',
    'container.build_id' => 'e538694c',
    'container.build_time' => 1582573374,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXKU5XO0');
